<center> 
Please use the form below to add a member
 <?php
$this->form->setAction($this->url());
echo $this->form;
?>



</center>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="application/javascript">
//function() {
//  alert("hi");
//  $("#birthday").datepicker();
//  $("#birthday").click(function(){
//
//  });}

//$( function() {
// $("#birthday").datepicker();
//} );
</script>
