<html> 
<head> 
<link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" /> 
<!--<script type="text/javascript" src="/js/site.js"></script> -->
<title>Online Book Store</title> 
</head>
<body> 
<!DOCTYPE html>
<html>
<head>
</head>
<body>
	<!-- HTML for SEARCH BAR -->
	<div id="tfheader1">
		<form id="tfnewsearch" method="get">
		        <input type="text" class="tftextinput" name="q" size="21" maxlength="120"><input type="submit" value="search" class="tfbutton" id="search" name="search">
		</form>
	<div class="tfclear"></div>  
	</div>
</body>

</html>




 <table> 
  <tr> 
   <td valign="top">  
	<table width="700"> 
   <tr align="bottom"> 
    <td class="value"><a href="/"><img src="/images/logo.jpg" border="0"  width="180"></a></td> 
    <td class="value"><a href="/books"><img src="/images/home.png" border="0"  width="55"></a></td> 
    <td class="value"><a href="/members"><img src="/images/register.png" border="0"  width="55"></a></td> 
    <td class="value"><a href="/books"><img src="/images/cart.png" border="0"  width="55"></a></td> 
    <td class="value"><a href="/books"><img src="/images/login.png" border="0"  width="55"></a></td> 
    <td class="value"><a href="/contact"><img src="/images/admin.png" border="0"  width="55"></a></td> 
  </tr>

  </table> 
     </td> 
  </tr> 
 </table> 


