
 <head>
 <link rel="stylesheet" type="text/css" media="screen" href="/css/main.css" />
<!-- <script type="text/javascript" src="/js/site.js"></script>-->
 <title>Online Book Store</title>
 </head>

 <header >
<!--  <table class="header_center">-->
<!--   <tr>-->
<!--    <td >-->
<!--      <table class="header_width">-->
<!--    <tr >-->
<!--     <td class="value"><a href="/"><img src="/images/logo.jpg" alt="logo" border="0"  width="180"></a></td>-->
<!--     <td class="value"><a href="/books"><img src="/images/home.png" alt="home" border="0"  width="55"></a></td>-->
<!--     <td class="value"><a href="/members"><img src="/images/register.png" alt="register" border="0"  width="55"></a></td>-->
<!--     <td class="value"><a href="/books"><img src="/images/cart.png" alt="cart" border="0"  width="55"></a></td>-->
<!--     <td class="value"><a href="/books"><img src="/images/login.png" alt="login" border="0"  width="55"></a></td>-->
<!--     <td class="value"><a href="/contact"><img src="/images/admin.png" alt="admin" border="0"  width="55"></a></td>-->
<!--   </tr>-->
<!--   </table>-->
<!--      </td>-->
<!--   </tr>-->
<!--  </table>-->

<nav class="clear">
 <ul >
  <li ><a href="/"><img src="/images/logo.jpg" alt="logo" border="0"  width="180"></a></li>
  <li ><a href="/books"><img src="/images/home.png" alt="home" border="0"  width="55"></a></li>
  <li ><a href="/auth/login"><img src="/images/register.png" alt="register" border="0"  width="55"></a></li>
  <li ><a href="/books"><img src="/images/cart.png" alt="cart" border="0"  width="55"></a></li>
  <li><a href="/books"><img src="/images/login.png" alt="login" border="0"  width="55"></a></li>
  <li ><a href="/contact"><img src="/images/admin.png" alt="admin" border="0"  width="55"></a></li>
 </ul>
</nav>
 </header>
