<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
        <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/styles.css" />
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="/js/jquery.datePicker.js"></script>
        <title>Online Book Store</title>
</head>

<body>
<section id="page">

        <?php
        include "header.phtml";        
        ?>
        <section id="articles">
                <div class="line"></div>

                <?php
                include "search.phtml";
                ?>

                <article id="books">
                        <?=$this->layout()->content; ?>
                </article>
        </section>








<?php
include "footer.phtml";
?>

</section>
</body>
</html>


